[tool.poetry]
name = "FileJacket"
version = "0.13.1"
description = "Package for abstracting file system handler in an oriented-object style."
authors = ["Gabriel <contato@gabrielfontenelle.com>"]
license = "GNU GENERAL PUBLIC LICENSE v3"
packages = [
    { include = "filejacket" },
]
include = [
    "filejacket/data/mime.types",
    "TODO",
    "LICENSE"
]

[tool.poetry.dependencies]
python = ">=3.11,<4"
Send2Trash = "^1.8"
psutil = "^7.0"
py7zr = "^0"
tinytag = "^2.1"
dill = "^0.4"
json-tricks = "^3.17"
rarfile = "^4"
tox-poetry = "^0.5"
Wand = "^0.6"
pillow = "^10.4"
opencv-python = "^4.11"
psd-tools = "^1.10"
imageio = {extras = ["pyav", "ffmpeg"], version = "^2.37"}
pymupdf = "^1.25"
av = "^15.1.0"
moviepy = "2.1.2"
pytz = "^2025.2"
requests = "^2.32"
typing-extensions = "^4.13"
polyfile = "^0.5"
httpx = "^0.28"
xxhash = "^3.5.0"
svglib = "^1.5.1"
toposort = "^1.10"
reportlab = "4.4.0"

[tool.poetry.group.dev.dependencies]
types-pillow = "^10.2.0.20240822"
types-psutil = "^6.1.0.20241102"
types-send2trash = "^1.8.2.7"
pytest = "*"
pytest-shutil = "^1.7.0"
mypy = "^1.8.0"
ruff = "^0.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
