[tool.poetry]
name = "Handler"
version = "0.2.5"
description = "Package for abstracting file system handler in an oriented-object style."
authors = ["Gabriel <colecionador.gabriel@gmail.com>"]
license = "MIT License"
include = [
    "handler/data/mime.types",
    "TODO"
]

[tool.poetry.dependencies]
python = "^3.7"
pytest-shutil = "^1.7.0"
pytest = "^6.2.1"
Send2Trash = "^1.5.0"
psutil = "^5.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
